# Generated by Django 5.1.7 on 2025-03-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": ("Пользователи",),
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
